using Factory.Cli.Models;
using Factory.Cli.Services;
using NJsonSchema.CodeGeneration.CSharp;
using NSwag.CodeGeneration.CSharp;

namespace Factory.Cli.Commands;

/// <summary>
/// IMPORT — load the third-party spec (and the product spec) and turn both into CLI-owned code
/// (journey step 2, slide 05 "Spec-aware"). Output is 100% regenerable; nobody edits it.
/// </summary>
public static class ImportCommand
{
    public static async Task<int> RunAsync(Workspace ws, string name)
    {
        var m = ws.LoadManifest(name);
        ConsoleUi.Step("IMPORT", $"connector '{name}'");

        var provider = await SpecService.LoadAsync(ws.Resolve(m.Provider.Spec));
        var product = await SpecService.LoadAsync(ws.Resolve(m.Product.Spec));
        ConsoleUi.Ok($"provider spec: {provider.Info?.Title} — {provider.Operations.Count()} operations, {provider.Components.Schemas.Count} schemas");
        ConsoleUi.Ok($"product spec:  {product.Info?.Title} — {product.Operations.Count()} operations, {product.Components.Schemas.Count} schemas");

        // Manifest sanity: every referenced operationId must exist in its spec.
        var errors = new List<string>();
        foreach (var op in m.Operations)
        {
            if (!product.Operations.Any(o => o.Operation.OperationId == op.ProductOperation))
                errors.Add($"operation '{op.Name}': product operationId '{op.ProductOperation}' not in product spec");
            foreach (var po in op.ProviderOperations)
                if (!provider.Operations.Any(o => o.Operation.OperationId == po))
                    errors.Add($"operation '{op.Name}': provider operationId '{po}' not in provider spec");
            if (!product.Components.Schemas.ContainsKey(op.CanonicalModel))
                errors.Add($"operation '{op.Name}': canonical model '{op.CanonicalModel}' not in product spec");
        }
        if (errors.Count > 0)
        {
            foreach (var e in errors) ConsoleUi.Fail(e);
            return 1;
        }
        ConsoleUi.Ok($"manifest references {m.Operations.Count} operation(s); all resolve against the specs");

        // 1) Provider client — NSwag, System.Text.Json, interface + class. Method names come from operationIds.
        var clientName = SpecService.Pascal(name) + "Client";
        var clientSettings = new CSharpClientGeneratorSettings
        {
            ClassName = clientName,
            GenerateClientInterfaces = true,
            GenerateClientClasses = true,
            GenerateDtoTypes = true,
            UseBaseUrl = false,            // relative URLs; HttpClient.BaseAddress comes from options (DI-owned)
            GenerateBaseUrlProperty = false,
            GenerateOptionalParameters = true,
            ExceptionClass = clientName + "Exception",
            CSharpGeneratorSettings =
            {
                Namespace = $"{m.Generation.Namespace}.Generated",
                JsonLibrary = CSharpJsonLibrary.SystemTextJson,
                GenerateNullableReferenceTypes = true,
                GenerateOptionalPropertiesAsNullable = true,
                GenerateDefaultValues = true,
            },
        };
        var clientCode = new CSharpClientGenerator(provider, clientSettings).GenerateFile();
        var clientPath = ws.Resolve($"{m.Generation.OutputRoot}/Generated/{clientName}.g.cs");
        WriteGenerated(ws, clientPath, Banner("provider client", m.Provider.Spec) + clientCode);

        // 2) Canonical models — DTOs only, no client. This is "product-models.ts" from the deck.
        var canonicalSettings = new CSharpClientGeneratorSettings
        {
            GenerateClientClasses = false,
            GenerateClientInterfaces = false,
            GenerateDtoTypes = true,
            CSharpGeneratorSettings =
            {
                Namespace = m.Generation.CanonicalNamespace,
                JsonLibrary = CSharpJsonLibrary.SystemTextJson,
                GenerateNullableReferenceTypes = true,
                GenerateOptionalPropertiesAsNullable = true,
                GenerateDefaultValues = true,
            },
        };
        var canonicalCode = new CSharpClientGenerator(product, canonicalSettings).GenerateFile();
        var canonicalPath = ws.Resolve($"{m.Generation.CanonicalProject}/Generated/CanonicalModels.g.cs");
        WriteGenerated(ws, canonicalPath, Banner("canonical models", m.Product.Spec) + canonicalCode);

        ConsoleUi.Info("Next: `integration-cli map " + name + "` to build the mapping context for the AI assistant.");
        return 0;
    }

    private static string Banner(string what, string spec) =>
        $"// <auto-generated>\n//   {what} generated by integration-cli import from {spec}\n//   CLI-owned. Safe to regenerate. DO NOT EDIT — edit the spec and re-run import.\n// </auto-generated>\n#nullable enable\n";

    private static void WriteGenerated(Workspace ws, string path, string content)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        ConsoleUi.Ok($"wrote {ws.Relative(path)} ({content.Split('\n').Length} lines)");
    }
}
